version: '2'

services:
  db:
    image: postgres:9.6.5
    environment:
      - POSTGRES_DB=async_web_service
      - POSTGRES_USER=async_web_service_admin
      - POSTGRES_PASSWORD=async_web_service_admin
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    command: postgres -c 'max_connections=500'
  web:
    build: .
    environment:
      - ALEMBIC_DB_CONNECT=postgresql://async_web_service_admin:async_web_service_admin@db/async_web_service
      - SQLALCHEMY_DB_CONNECT_STRING=postgresql+asyncpg://async_web_service_admin:async_web_service_admin@db/async_web_service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./src:/code
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  pgdata:
