"""Add subscriptions table

Revision ID: 1f896cf9134d
Revises: 9b2a936577d2
Create Date: 2021-07-06 20:32:17.172791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f896cf9134d'
down_revision = '9b2a936577d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subs',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subscribe_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscribe_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscribe_to_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subs')
    # ### end Alembic commands ###
